import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Footer from "@/components/ui/footer";
import NavBar from "@/components/ui/nav";
import { Toaster } from "@/components/ui/toast/toaster";
import Providers from "@/providers";

import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elite Wholesale",
  description: "Generated by create next app",
  keywords: "elite, wholesale, elite wholesale, vapes, vape store",
  icons: {
    icon: "/icon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${montserrat.className} flex flex-col min-h-screen`}
      >
        <div className="mb-8">
          <NavBar />
        </div>

        <Providers>
          <main className="px-5 sm:px-24 md:px-36 xl:px-[30rem]">
            {children}
          </main>
        </Providers>
        <Toaster />

        <div className="mt-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
