import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import NavBar from "@/components/ui/nav";

import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elite Wholesale",
  description: "Generated by create next app",
  keywords: "elite, wholesale, elite wholesale, vapes, vape store",
  icons: {
    icon: "/icon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={montserrat.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
